### ISSUE TITLE
Potential gulp Improvements

### ISSUE THREAD

**Issue by ataylorme** [ahmadawais/WPGulp#113]
I just found this project - stellar job on making something so great! I see in v2 the project was updated to use gulp 4.

[WP Rig](https://github.com/wprig/wprig) recently went through a gulp 4 overhaul for the upcoming 1.1 version. 

See [this pull request](https://github.com/wprig/wprig/pull/47) for the list of all the improvements made. 

I think quite a few of them, such as using `pump`, loading plugins and splitting tasks into separate files, could be implemented in WPGulp as well.

Would you be interested in having any of the gulp 4 improvements we made to WP Rig in WPGulp?

**Comment by ahmadawais** [comment]
>I just found this project - stellar job on making something so great! I see in v2 the project was updated to use gulp 4.

@ataylorme nice to finally e-meet you. I think I heard about you/your work at Pantheon from David. So, 👋 fellow dev 🥑. 

>WP Rig recently went through a gulp 4 overhaul for the upcoming 1.1 version.
See this pull request for the list of all the improvements made.

Just went through it.

>I think quite a few of them, such as using pump, loading plugins and splitting tasks into separate files, could be implemented in WPGulp as well. Would you be interested in having any of the gulp 4 improvements we made to WP Rig in WPGulp?

- Interested — **YES**
- Loading plugins — I see no value in that, guess-work makes things harder for beginners, many people like to remove things from this setup.
- `pump` — that is super awesome. Didn't know about it. Send a PR for that.
- Splitting files — I think that WP devs run away from complex tooling projects. Splitting files while ideal, it does leave us with an extra folder that mostly scares the beginner developers (who are the target of this tool) — I want them to think "It's just one gulp file, how hard could it be" — instead of dealing with a lot of moving parts. That's also in part why this project has been successful. So, for now, a soft **NO** on splitting files.

I'd be looking forward to your PR's. Make sure that you follow [Emoji Log](https://github.com/ahmadawais/Emoji-Log) for your git commit messages. It's how this project is maintained since after v1.3.

Looking forward, peace! ✌️

**Comment by ataylorme** [comment]
@ahmadawais thanks for the quick reply. Nice to "meet" you as well!

Understood that the project is aimed at beginners so the change we want is to use `pump` instead of `pipe` (see the gulp 4.0.0 docs on [why use pump](https://github.com/gulpjs/gulp/tree/master/docs/why-use-pump)).
