### ISSUE TITLE
How to use bower files in END PRODUCT

### ISSUE THREAD

**Issue by bEnnAbEEL** [ahmadawais/WPGulp#138]
I have a very serious question posted here regarding your article.
https://stackoverflow.com/questions/54469515/how-to-include-bower-components-files-css-js-from-any-framework-in-end-product

Can you please have a look and let help me out here.

**Comment by JeremyEnglert** [comment]
You have multiple options.

1. Just upload the bower files. I'm not understanding why you can't do this.
2. Bundle all of the bower files into a single JS file that lives in your theme instead of in the bower directory.
3. Setup gulp to move the bower files you want into a different directory.

You have multiple options. It's just whatever works best for you.
