### ISSUE TITLE
(Bad boy admin@snapgravy.com	Gregory Matthews)

### ISSUE THREAD

**Issue by WPGulpPro** [ahmadawais/WPGulp#142]
The CSS produced by your SASS workflow produces incorrect CSS declarations. Fix ASAP.

**Comment by ahmadawais** [comment]
The funniest thing is happening — that's bad — Gregory Matthews(admin@snapgravy.com) after being unable to bully me into getting free of cost support for my open source work is trying to spam my repositories with a fake GitHub profile. 

Reported your fake profile :)

Also, let me send you the message you crafted for me when you couldn't pay up.

### This message is being returned undelivered due to MX filtering rules and regulations. The message sender has also been previously added to the no contact list and will be reported as such to the originating SMTP server ###

LOL. Internet is so funny today!
