### ISSUE TITLE
💯 ES6 or ESNext Support

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/WPGulp#67]
WPGulp 2.0 needs to support ES6/7/8 or let's call it ESNext. I am open to suggestions on how we can handle this. This is a two-fold issue and the todo list is as follows:

- [ ] Convert JS to ESNext
- [ ] Convert WPGulp's code into ESNext

Peace! ✌️

**Comment by kbooshco** [comment]
This would be the best thing to happen to WPGulp.

**Comment by dingo-d** [comment]
Ok, so I've been reading about Prettier, and I talked with my colleagues from work what they think about it. So I have a few questions about the usage of Prettier.

It's a code formatting tool. When you are writing a project from zero, what benefits do you have over just defining formatting rules in ESLint?
You can set up the rules that will say to put certain function calls on separate lines, specify max width of a line etc. If you have linters set up in your editor or IDE the linter will notify you of this.

Would Prettier be used just for JS or JS and PHP? What about [WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/)? From the discussion that is going on there, I think there is an incentive to put together official WordPress handbook with them. And PHPCS can check, and beautify (through the usage of `phpcbf`) your JS, CSS and PHP code.

Or should Prettier be used when you want to 'WPGulpify' your existing WP project?

The feedback I got from my colleagues (who are experts at JS) is that it makes no sense to add Prettier to the project that is starting from zero (because you need to follow the set guidelines that exist, plus use existing linting rules). And when you want to add it to the existing project it can be pretty hard to configure to work well with linters (one colleague said that it messed his code quite a bit so he had to undo the changes done by the Prettier).

So I'd like some really good examples where Prettier excels and where we can have a good use case for it (other than riding the hype train :D).

**Comment by ahmadawais** [comment]
@dingo-d thanks for commenting here. I have been tracking the ESLint + Prettier integration in a separate issue here #73 — I think we should discuss it there instead of this issue. Check my comments there.
