### ISSUE TITLE
WP POT Support

### ISSUE THREAD

**Issue by danieliser** [ahmadawais/WPGulp#8]
I love gulp, use it for my plugin builds, and just found this repo.

In Popup Maker and its extensions we use gulp-wp-pot to automatically scan and update a translation.pot file.

I believe I got a few tips from your first guide for our routines, but mine have a few more things I have added for extra awesomeness.

A few things you could merge here would be

POT Langpack creation - Watcher on **/*.php
Automated Build Cycle (Ours uses the package.json data to copy build assets into a named directory and then zips with the current version number like popup-maker_v1.4.7.zip)

Also from testing, csso works better than uglifycss and why not include gulp-load-plugins and skip the declarations alltogether?

You can see our POT & build tasks here https://github.com/PopupMaker/Popup-Maker/blob/master/gulpfile.js#L72

**Comment by ahmadawais** [comment]
@danieliser Thanks for dropping by.

I have been thinking to update this repo, I have a lot more routines in my personal workflow as compared to this one. POT files is a definite feature. I plan to add it here. You are more than welcomed to submit a PR.

Build routines are not added because everyone deals with it in a different manner. I am planning to add a simple zip building routine in there. But trying to keep everything as generic and portable as I can.

Can you explain how and why CSSO is better than UglifyCSS?

Again, to keep things portable I have not used gulp-load-plugins module. It helps when you are trying to debug and want to ignore any single module.

**Comment by ahmadawais** [comment]
@danieliser POT file generation support is here.

**Comment by danieliser** [comment]
Nice
