### ISSUE TITLE
Discussion: Remove Gulp Global Dependency in 2.0

### ISSUE THREAD

**Issue by JeremyEnglert** [ahmadawais/WPGulp#81]
Since we're moving to Gulp 4 with 2.0, I propose we drop the global Gulp dependency. Many users will have legacy projects running on Gulp 3, which will break if Gulp 4 is installed globally.

From a users perspective, the largest change would be how tasks are called. Instead of running `gulp`, a user would run `npm run gulp`. This applies to other tasks as well - `gulp vendorsJS` becomes `npm run vendorsJS`.

If this is a change we would like to move forward with, I would be happy to implement and push a PR.

**Comment by ahmadawais** [comment]
@JeremyEnglert You are right about that. I have been thinking about this all along since the initial versions of this project. I think it's time we move from simply running `gulp` towards running (what now is considered an industry standard) `npm start` and the NPM Scripts, they understand the `./node_modules/.bin/` by adding it to the `$PATH` and thus having access to it.

For further reading: https://firstdoit.com/no-need-for-globals-using-npm-dependencies-in-npm-scripts-3dfb478908

**Comment by JeremyEnglert** [comment]
I'll add this to my list. I'll try to get a PR pushed up later today. As this should make it easier for users to contribute to the new project.

**Comment by JeremyEnglert** [comment]
Done in https://github.com/ahmadawais/WPGulp/pull/83.
